//THEME
export const SWITCH_THEME = 'SWITCH_THEME';

//CHARTS
export const FETCH_CHARTS = 'FETCH_CHARTS';
export const FETCH_CHARTS_SUCCESS = 'FETCH_CHARTS_SUCCESS';
export const FETCH_CHARTS_ERROR = 'FETCH_CHARTS_ERROR';
export const SET_PERIOD_CHART = 'SET_PERIOD_CHART';

//MARKETS
export const FETCH_SNX_CURRENCY = 'FETCH_SNX_CURRENCY';
export const FETCH_SNX_CURRENCY_SUCCESS = 'FETCH_SNX_CURRENCY_SUCCESS';
export const FETCH_SNX_CURRENCY_ERROR = 'FETCH_SNX_CURRENCY_ERROR';
export const FETCH_NUSD_CURRENCY = 'FETCH_NUSD_CURRENCY';
export const FETCH_NUSD_CURRENCY_SUCCESS = 'FETCH_NUSD_CURRENCY_SUCCESS';
export const FETCH_NUSD_CURRENCY_ERROR = 'FETCH_NUSD_CURRENCY_ERROR';

//EXCHANGE
export const FETCH_OPEN_INTEREST = 'FETCH_OPEN_INTEREST';
export const FETCH_OPEN_INTEREST_SUCCESS = 'FETCH_OPEN_INTEREST_SUCESS';
export const FETCH_TRADING_VOLUME = 'FETCH_TRADING_VOLUME';
export const FETCH_TRADING_VOLUME_SUCCESS = 'FETCH_TRADING_VOLUME_SUCCESS';

export const FETCH_UNISWAP_DATA = 'FETCH_UNISWAP_DATA';
export const FETCH_UNISWAP_DATA_SUCCESS = 'FETCH_UNISWAP_DATA_SUCCESS';

// NETWORK
export const FETCH_NETWORK_DATA = 'FETCH_NETWORK_DATA';
export const FETCH_NETWORK_DATA_SUCCESS = 'FETCH_NETWORK_DATA_SUCCESS';
export const FETCH_NETWORK_FEES = 'FETCH_NETWORK_FEES';
export const FETCH_NETWORK_FEES_SUCCESS = 'FETCH_NETWORK_FEES_SUCCESS';
export const FETCH_NETWORK_DEPOT = 'FETCH_NETWORK_DEPOT';
export const FETCH_NETWORK_DEPOT_SUCCESS = 'FETCH_NETWORK_DEPOT_SUCCESS';

// BINARY OPTIONS
export const FETCH_BINARY_OPTIONS_MARKETS = 'FETCH_BINARY_OPTIONS_MARKETS';
export const FETCH_BINARY_OPTIONS_TRANSACTIONS = 'FETCH_BINARY_OPTIONS_TRANSACTIONS';
export const FETCH_BINARY_OPTIONS_MARKETS_SUCCESS = 'FETCH_BINARY_OPTIONS_MARKETS_SUCCESS';
export const FETCH_BINARY_OPTIONS_TRANSACTIONS_SUCCESS =
	'FETCH_BINARY_OPTIONS_TRANSACTIONS_SUCCESS';
