//THEME
export const SWITCH_THEME = "SWITCH_THEME";

//CHARTS
export const FETCH_CHARTS = "FETCH_CHARTS";
export const FETCH_CHARTS_SUCCESS = "FETCH_CHARTS_SUCCESS";
export const FETCH_CHARTS_ERROR = "FETCH_CHARTS_ERROR";
export const SET_PERIOD_CHART = "SET_PERIOD_CHART";

//MARKETS
export const FETCH_HAV_CURRENCY = "FETCH_HAV_CURRENCY";
export const FETCH_HAV_CURRENCY_SUCCESS = "FETCH_HAV_CURRENCY_SUCCESS";
export const FETCH_HAV_CURRENCY_ERROR = "FETCH_HAV_CURRENCY_ERROR";
export const FETCH_NUSD_CURRENCY = "FETCH_NUSD_CURRENCY";
export const FETCH_NUSD_CURRENCY_SUCCESS = "FETCH_NUSD_CURRENCY_SUCCESS";
export const FETCH_NUSD_CURRENCY_ERROR = "FETCH_NUSD_CURRENCY_ERROR";

export const FETCH_COINMARKETCAP_HAV = "FETCH_COINMARKETCAP_HAV";
export const FETCH_COINMARKETCAP_HAV_SUCCESS = "FETCH_COINMARKETCAP_HAV_SUCCESS";
export const FETCH_COINMARKETCAP_HAV_ERROR = "FETCH_COINMARKETCAP_HAV_ERROR";

export const FETCH_COINMARKETCAP_NUSD = "FETCH_COINMARKETCAP_NUSD";
export const FETCH_COINMARKETCAP_NUSD_SUCCESS = "FETCH_COINMARKETCAP_NUSD_SUCCESS";
export const FETCH_COINMARKETCAP_NUSD_ERROR = "FETCH_COINMARKETCAP_NUSD_ERROR";


